apiVersion: v1
kind: Namespace
metadata:
  name: kube-system

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: my-app
  name: my-app
  namespace: kube-system

---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: my-app
  name: my-app
  namespace: kube-system
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    k8s-app: my-app
  type: LoadBalancer

---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: my-app
  name: my-app
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: my-app
  template:
    metadata:
      labels:
        k8s-app: my-app
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'runtime/default'
    spec:
      containers:
        - name: my-app
          image: swenson11/my-resume:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 30
          
      serviceAccountName: my-app
      nodeSelector:
        "beta.kubernetes.io/os": linux
   